export const GALGAME_RESOURCE_TYPE_ICON_MAP: Record<string, string> = {
  game: 'lucide:box',
  patch: 'lucide:puzzle',
  collection: 'lucide:boxes',
  voice: 'lucide:music-4',
  image: 'lucide:image',
  ai: 'simple-icons:openai',
  video: 'lucide:video',
  others: 'lucide:ellipsis'
}

export const GALGAME_RESOURCE_PLATFORM_ICON_MAP: Record<string, string> = {
  windows: 'ant-design:windows-outlined',
  mac: 'iconoir:apple-mac',
  linux: 'ant-design:linux-outlined',
  emulator: 'lucide:terminal',
  app: 'lucide:smartphone',
  others: 'lucide:ellipsis'
}

export const GALGAME_RESOURCE_PROVIDER_MAP: Record<string, string> = {
  magnet: '磁力下载',
  'baidu.com': '百度网盘',
  'quark.cn': '夸克网盘',
  'alipan.com': '阿里云盘',
  '123912.com': '123 云盘',
  '123865.com': '123 云盘',
  '123pan.com': '123 云盘',
  '123pan.cn': '123 云盘',
  'xunlei.com': '迅雷云盘',
  'weiyun.com': '腾讯微云',
  '139.com': '和彩云 (移动云盘)',
  '189.cn': '天翼云盘',
  'uc.cn': 'UC 网盘',
  lanzou: '蓝奏云',
  'ctfile.com': '城通网盘',
  'nullcloud.top': '未知云盘',
  'mypikpak.com': 'PikPak',
  'sharepoint.com': 'OneDrive',
  'sharepoint.cn': 'OneDrive',
  '1drv.ms': 'OneDrive',
  'mega.nz': 'MEGA',
  'google.com': 'Google 云破案',
  'yandex.com': 'Yandex Disk',
  'gofile.io': 'GoFile',
  'ipfs.dweb.link': 'IPFS',
  'steampowered.com': 'Steam',
  'epicgames.com': 'Epic 游戏商店',
  'itch.io': 'itch.io',
  'github.com': 'GitHub',
  'bilibili.com': '哔哩哔哩',
  'tieba.baidu.com': '百度贴吧',
  't.me': 'Telegram',
  'archive.org': 'Internet Archive',
  'nyaa.si': 'Nyaa',
  '2dfan.com': '2BFun',
  'ddfan.org': '2BFun',
  'ddfan.top': '2BFun',
  'galge.top': '2BFun',
  'hacg.uno': '琉璃神社 (HACG)',
  'kungal.com': '鲲 Galgame 论坛',
  'moyu.moe': '鲲 Galgame 补丁',
  'anime-sharing.com': 'Anime-Sharing',
  'e-hentai.org': 'E-Hentai',
  'dmm.co.jp': 'DMM',
  'zi6.cc': '梓澪',
  'zi0.cc': '梓澪',
  'zi8.cc': '梓澪',
  'shinnku.com': '真红小站',
  'shinnku.org': '真红小站',
  'oo0o.ooo': '真红小站',
  'touchgal.io': 'TouchGal',
  'touchgal.us': 'TouchGal',
  'dlgal.com': 'GGbases'
}
